In [1]:
import numpy as np
import seaborn as sns
import pandas as pd
from sklearn.tree import DecisionTreeRegressor

In [8]:
data = pd.read_csv("model/survey.csv")
data.head()

Jenis Kelamin  Umur Lokasi    Mood Rekomendasi Makanan Rekomendasi Minuman
0   Laki - Laki    17    NaN  Senang         Nasi goreng     Minuman bersoda
1   Laki - Laki    17    NaN  Senang             Cokelat     Minuman bersoda
2   Laki - Laki    17    NaN   Marah           Mie pedas         Air mineral
3   Laki - Laki    20    NaN   Marah              Seblak         Air mineral
4   Laki - Laki    25    NaN   Sedih       Sayur-sayuran                 Teh

In [14]:
sex = data["Jenis Kelamin"]
age = data["Umur"]
mood = data["Mood"]
food = data["Rekomendasi Makanan"]
drink = data['Rekomendasi Minuman']

In [5]:
data['Lokasi'] = data['Lokasi'].fillna("Tidak Tersedia")
data.head()

Jenis Kelamin  Umur          Lokasi    Mood Rekomendasi Makanan  \
0   Laki - Laki    17  Tidak Tersedia  Senang         Nasi goreng   
1   Laki - Laki    17  Tidak Tersedia  Senang             Cokelat   
2   Laki - Laki    17  Tidak Tersedia   Marah           Mie pedas   
3   Laki - Laki    20  Tidak Tersedia   Marah              Seblak   
4   Laki - Laki    25  Tidak Tersedia   Sedih       Sayur-sayuran   

  Rekomendasi Minuman  
0     Minuman bersoda  
1     Minuman bersoda  
2         Air mineral  
3         Air mineral  
4                 Teh

Encoding 

In [ ]:
def simplify_age (age):
    if age > 0 and age < 6:
        return "Balita"
    elif age > 6 and age < 12:
        return "Anak - anak"
    elif age > 12 and age < 18:
        return "Remaja"
    elif age > 18 and age < 65:
        return "Dewasa"
    elif age > 65 and age < 200:
        return "lansia"
    return "Tidak normal"

data["Umur"] = data["Umur"].apply(simplify_age)
data["Umur"].unique()

In [23]:
data.head()

Jenis Kelamin  Umur Lokasi    Mood Rekomendasi Makanan Rekomendasi Minuman  \
0              0     3    NaN  Senang         Nasi goreng     Minuman bersoda   
1              0     3    NaN  Senang             Cokelat     Minuman bersoda   
2              0     3    NaN   Marah           Mie pedas         Air mineral   
3              0     2    NaN   Marah              Seblak         Air mineral   
4              0     2    NaN   Sedih       Sayur-sayuran                 Teh   

     umur  
0  Remaja  
1  Remaja  
2  Remaja  
3  Dewasa  
4  Dewasa

In [15]:
from sklearn.preprocessing import LabelEncoder
le_sex = LabelEncoder()
data['Jenis Kelamin'] = le_sex.fit_transform(data['Jenis Kelamin'])
data["Jenis Kelamin"].unique()

array([0, 1])

In [24]:
le_age = LabelEncoder()
data["Umur"] = le_age.fit_transform(data["Umur"])
data["Umur"].unique()

array([3, 2, 4, 0, 1, 5], dtype=int64)

In [25]:
le_mood = LabelEncoder()
data["Mood"] = le_mood.fit_transform(data["Umur"])
data["Mood"].unique()

array([3, 2, 4, 0, 1, 5], dtype=int64)

In [6]:
x = data["Jenis Kelamin", "Umur", "Mood"]
y = data["Rekomendasi Makanan", "Rekomendasi Minuman"]

KeyError: ('Jenis Kelamin', 'Umur', 'Mood')

In [4]:
regressor = DecisionTreeRegressor(random_state=0)
regressor.fit(X, y)

NameError: name 'X' is not defined