Change ";" into ","

In [77]:
import os
with open('model/test.csv', 'r') as file:
    filedata = file.read()
    filedata = filedata.replace(';', ',')

    with open('model/test.csv', 'w') as file:
        file.write(filedata)

CODE STARTS HERE

In [1]:
import numpy as np
import seaborn as sns
import pandas as pd
from sklearn.tree import DecisionTreeRegressor

In [65]:
data = pd.read_csv("model/survey.csv")
test = pd.read_csv("model/test.csv")
data.head()

Jenis Kelamin  Umur Lokasi    Mood Rekomendasi Makanan Rekomendasi Minuman
0   Laki - Laki    17    NaN  Senang         Nasi goreng     Minuman bersoda
1   Laki - Laki    17    NaN  Senang             Cokelat     Minuman bersoda
2   Laki - Laki    17    NaN   Marah           Mie pedas         Air mineral
3   Laki - Laki    20    NaN   Marah              Seblak         Air mineral
4   Laki - Laki    25    NaN   Sedih       Sayur-sayuran                 Teh

In [14]:
sex = data["Jenis Kelamin"]
age = data["Umur"]
mood = data["Mood"]
food = data["Rekomendasi Makanan"]
drink = data['Rekomendasi Minuman']

In [66]:
data['Lokasi'] = data['Lokasi'].fillna("Tidak Tersedia")
data.head()

Jenis Kelamin  Umur          Lokasi    Mood Rekomendasi Makanan  \
0   Laki - Laki    17  Tidak Tersedia  Senang         Nasi goreng   
1   Laki - Laki    17  Tidak Tersedia  Senang             Cokelat   
2   Laki - Laki    17  Tidak Tersedia   Marah           Mie pedas   
3   Laki - Laki    20  Tidak Tersedia   Marah              Seblak   
4   Laki - Laki    25  Tidak Tersedia   Sedih       Sayur-sayuran   

  Rekomendasi Minuman  
0     Minuman bersoda  
1     Minuman bersoda  
2         Air mineral  
3         Air mineral  
4                 Teh

Encoding 

In [ ]:
def simplify_age (age):
    if age > 0 and age < 6:
        return "Balita"
    elif age > 6 and age < 12:
        return "Anak - anak"
    elif age > 12 and age < 18:
        return "Remaja"
    elif age > 18 and age < 65:
        return "Dewasa"
    elif age > 65 and age < 200:
        return "lansia"
    return "Tidak normal"

data["Umur"] = data["Umur"].apply(simplify_age)
data["Umur"].unique()

In [69]:
data.head()

Jenis Kelamin    Umur          Lokasi    Mood Rekomendasi Makanan  \
0   Laki - Laki  Remaja  Tidak Tersedia  Senang         Nasi goreng   
1   Laki - Laki  Remaja  Tidak Tersedia  Senang             Cokelat   
2   Laki - Laki  Remaja  Tidak Tersedia   Marah           Mie pedas   
3   Laki - Laki  Dewasa  Tidak Tersedia   Marah              Seblak   
4   Laki - Laki  Dewasa  Tidak Tersedia   Sedih       Sayur-sayuran   

  Rekomendasi Minuman  
0     Minuman bersoda  
1     Minuman bersoda  
2         Air mineral  
3         Air mineral  
4                 Teh

In [70]:
from sklearn.preprocessing import LabelEncoder
le_sex = LabelEncoder()
data['Jenis Kelamin'] = le_sex.fit_transform(data['Jenis Kelamin'])
data["Jenis Kelamin"].unique()

array([0, 1])

In [71]:
le_age = LabelEncoder()
data["Umur"] = le_age.fit_transform(data["Umur"])
data["Umur"].unique()

array([3, 2, 4, 0, 1, 5])

In [72]:
le_mood = LabelEncoder()
data["Mood"] = le_mood.fit_transform(data["Mood"])
data["Mood"].unique()

array([2, 0, 1])

In [73]:
le_food = LabelEncoder()
data["Rekomendasi Makanan"] = le_food.fit_transform(data["Rekomendasi Makanan"])
data["Rekomendasi Makanan"].unique()

array([6, 0, 5, 8, 7, 1, 3, 9, 4, 2])

In [74]:
le_drink = LabelEncoder()
data["Rekomendasi Minuman"] = le_drink.fit_transform(data["Rekomendasi Minuman"])
data["Rekomendasi Minuman"].unique()

array([5, 1, 7, 2, 4, 0, 6, 3, 8])

USE TO INVERSE

In [ ]:
data['Mood'] = le_mood.inverse_transform(data["Mood"])
data['Mood'].unique()

array(['Senang', 'Marah', 'Sedih'], dtype=object)

MACHINE LEARNING START HERE

In [53]:
data.head()

Jenis Kelamin  Umur          Lokasi  Mood  Rekomendasi Makanan  \
0              0     3  Tidak Tersedia     2                    6   
1              0     3  Tidak Tersedia     2                    0   
2              0     3  Tidak Tersedia     0                    5   
3              0     2  Tidak Tersedia     0                    8   
4              0     2  Tidak Tersedia     1                    7   

   Rekomendasi Minuman  
0                    5  
1                    5  
2                    1  
3                    1  
4                    7

In [62]:
features = ["Jenis Kelamin", "Umur", "Mood"]
X = data[features]
y = data["Rekomendasi Makanan"]
z = data["Rekomendasi Minuman"]
X.head()

Jenis Kelamin  Umur  Mood
0              0     3     2
1              0     3     2
2              0     3     0
3              0     2     0
4              0     2     1

In [63]:
regressorFood = DecisionTreeRegressor(random_state=0)
regressorDrink = DecisionTreeRegressor(random_state=0)
regressorFood.fit(X, y)
regressorDrink.fit(X,z)

DecisionTreeRegressor(random_state=0)

In [64]:
y_pred = regressorFood.predict(X)
z_pred = regressorDrink.predict(X)