# Read Only, Don't Execute

Change ";" into ","

In [ ]:
import os
with open('model/test.csv', 'r') as file:
    filedata = file.read()
    filedata = filedata.replace(';', ',')

    with open('model/test.csv', 'w') as file:
        file.write(filedata)

To inverse Label encoding, simply run

<font color = 'red'>[corresponding Label Encoder variable]</font>.inverse_transform(<font color = 'red'>[value]</font>)

Example

In [ ]:
#leA = Label Encoder for age
leA.inverse_transform([0])
#will print out "Anak - anak"

To inverse OneHotEncoder however:

In [ ]:
#y is the variable that's already encoded
for i in y:
  i = np.argmax(i)

# CODE STARTS HERE

In [1]:
import numpy as np
import seaborn as sns
import pandas as pd
from sklearn.tree import DecisionTreeRegressor
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [35]:
data = pd.read_csv("model/survey.csv")
data.head()

Jenis Kelamin  Umur Lokasi    Mood Rekomendasi Makanan Rekomendasi Minuman
0   Laki - Laki    17    NaN  Senang         Nasi goreng     Minuman bersoda
1   Laki - Laki    17    NaN  Senang             Cokelat     Minuman bersoda
2   Laki - Laki    17    NaN   Marah           Mie pedas         Air mineral
3   Laki - Laki    20    NaN   Marah              Seblak         Air mineral
4   Laki - Laki    25    NaN   Sedih       Sayur-sayuran                 Teh

In [36]:
data['Lokasi'] = data['Lokasi'].fillna("Tidak Tersedia")
data.head()

Jenis Kelamin  Umur          Lokasi    Mood Rekomendasi Makanan  \
0   Laki - Laki    17  Tidak Tersedia  Senang         Nasi goreng   
1   Laki - Laki    17  Tidak Tersedia  Senang             Cokelat   
2   Laki - Laki    17  Tidak Tersedia   Marah           Mie pedas   
3   Laki - Laki    20  Tidak Tersedia   Marah              Seblak   
4   Laki - Laki    25  Tidak Tersedia   Sedih       Sayur-sayuran   

  Rekomendasi Minuman  
0     Minuman bersoda  
1     Minuman bersoda  
2         Air mineral  
3         Air mineral  
4                 Teh

## Encoding 

In [37]:
def simplify_age (age):
    if age > 0 and age < 6:
        return "Balita"
    elif age > 6 and age < 12:
        return "Anak - anak"
    elif age > 12 and age < 18:
        return "Remaja"
    elif age > 18 and age < 65:
        return "Dewasa"
    elif age > 65 and age < 200:
        return "lansia"
    return "Tidak normal"

data["Umur"] = data["Umur"].apply(simplify_age)
data["Umur"].unique()

array(['Remaja', 'Dewasa', 'Tidak normal', 'Anak - anak', 'Balita',
       'lansia'], dtype=object)

In [38]:
sex = data["Jenis Kelamin"]
age = data["Umur"]
mood = data["Mood"]
food = data["Rekomendasi Makanan"]
drink = data['Rekomendasi Minuman']

In [39]:
sex.value_counts()

Perempuan      55
Laki - Laki    44
Name: Jenis Kelamin, dtype: int64

In [41]:
age.value_counts()

Remaja          44
Dewasa          24
Anak - anak     15
Tidak normal     7
lansia           7
Balita           2
Name: Umur, dtype: int64

In [40]:
data = data[data.Umur != "Tidak normal"]
data = data[data["Rekomendasi Minuman"] != "susu"]

In [42]:
data.head()
data.describe()

Jenis Kelamin    Umur  Lokasi    Mood Rekomendasi Makanan  \
count             91      91      91      91                  91   
unique             2       5      34       3                  10   
top        Perempuan  Remaja  Amogus  Senang         Nasi goreng   
freq              49      44      28      49                  16   

       Rekomendasi Minuman  
count                   91  
unique                   8  
top            Air mineral  
freq                    19

In [43]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
ohe = OneHotEncoder()
leS = LabelEncoder()
leA = LabelEncoder()
leM = LabelEncoder()
leF = LabelEncoder()
leD = LabelEncoder()

## CHANGE DATATYPE TO CATEGORY

In [44]:
data[["Jenis Kelamin", "Umur", "Mood", "Rekomendasi Makanan", "Rekomendasi Minuman"]] = data[["Jenis Kelamin", "Umur", "Mood", "Rekomendasi Makanan", "Rekomendasi Minuman"]].astype('category')

In [45]:
print(f"Jenis Kelamin: ", sex.unique())
print(f"Umur: ", age.unique())
print(f"Mood: ", mood.unique())
print(f"Makanan: ", food.unique())
print(f"Minuman: ", drink.unique())

Jenis Kelamin:  ['Laki - Laki' 'Perempuan']
Umur:  ['Remaja' 'Dewasa' 'Tidak normal' 'Anak - anak' 'Balita' 'lansia']
Mood:  ['Senang' 'Marah' 'Sedih']
Makanan:  ['Nasi goreng' 'Cokelat' 'Mie pedas' 'Seblak' 'Sayur-sayuran' 'Daging'
 'Kacang-kacangan' 'Telur' 'Makanan laut' 'Ikan-ikanan']
Minuman:  ['Minuman bersoda' 'Air mineral' 'Teh' 'Es krim' 'Kopi' 'Air kelapa'
 'Susu' 'Jus' 'susu']


In [46]:
data["sex_LE"] = leS.fit_transform(data["Jenis Kelamin"])
data["age_LE"] = leA.fit_transform(data["Umur"])
data["mood_LE"] = leM.fit_transform(data["Mood"])
data["food_LE"] = leF.fit_transform(data["Rekomendasi Makanan"])
data["drink_LE"] = leD.fit_transform(data["Rekomendasi Minuman"])

In [47]:
data.head()

Jenis Kelamin    Umur          Lokasi    Mood Rekomendasi Makanan  \
0   Laki - Laki  Remaja  Tidak Tersedia  Senang         Nasi goreng   
1   Laki - Laki  Remaja  Tidak Tersedia  Senang             Cokelat   
2   Laki - Laki  Remaja  Tidak Tersedia   Marah           Mie pedas   
3   Laki - Laki  Dewasa  Tidak Tersedia   Marah              Seblak   
4   Laki - Laki  Dewasa  Tidak Tersedia   Sedih       Sayur-sayuran   

  Rekomendasi Minuman  sex_LE  age_LE  mood_LE  food_LE  drink_LE  
0     Minuman bersoda       0       3        2        6         5  
1     Minuman bersoda       0       3        2        0         5  
2         Air mineral       0       3        0        5         1  
3         Air mineral       0       2        0        8         1  
4                 Teh       0       2        1        7         7

# MACHINE LEARNING START HERE

In [15]:
data.head()

Jenis Kelamin    Umur          Lokasi    Mood Rekomendasi Makanan  \
0   Laki - Laki  Remaja  Tidak Tersedia  Senang         Nasi goreng   
1   Laki - Laki  Remaja  Tidak Tersedia  Senang             Cokelat   
2   Laki - Laki  Remaja  Tidak Tersedia   Marah           Mie pedas   
3   Laki - Laki  Dewasa  Tidak Tersedia   Marah              Seblak   
4   Laki - Laki  Dewasa  Tidak Tersedia   Sedih       Sayur-sayuran   

  Rekomendasi Minuman  sex_LE  age_LE  mood_LE  food_LE  drink_LE  
0     Minuman bersoda       0       3        2        6         5  
1     Minuman bersoda       0       3        2        0         5  
2         Air mineral       0       3        0        5         1  
3         Air mineral       0       2        0        8         1  
4                 Teh       0       2        1        7         7

In [16]:
from sklearn.model_selection import train_test_split

Put data into variable

In [48]:
X = data[["sex_LE","age_LE", "mood_LE"]].values
X

array([[0, 3, 2],
       [0, 3, 2],
       [0, 3, 0],
       [0, 2, 0],
       [0, 2, 1],
       [0, 0, 2],
       [1, 3, 0],
       [1, 3, 2],
       [0, 0, 1],
       [1, 0, 2],
       [0, 0, 1],
       [0, 0, 2],
       [0, 2, 2],
       [0, 3, 1],
       [1, 3, 0],
       [0, 3, 2],
       [0, 2, 1],
       [0, 3, 0],
       [1, 3, 0],
       [0, 3, 2],
       [0, 3, 1],
       [1, 3, 2],
       [1, 3, 2],
       [1, 3, 1],
       [1, 3, 2],
       [1, 3, 2],
       [1, 3, 2],
       [1, 3, 2],
       [1, 3, 2],
       [1, 2, 2],
       [1, 3, 1],
       [0, 3, 2],
       [0, 3, 2],
       [1, 3, 0],
       [1, 3, 2],
       [0, 2, 2],
       [1, 3, 2],
       [0, 3, 0],
       [0, 1, 2],
       [0, 3, 2],
       [1, 3, 2],
       [0, 0, 2],
       [1, 0, 2],
       [0, 0, 0],
       [1, 0, 0],
       [1, 3, 2],
       [1, 3, 2],
       [1, 3, 1],
       [1, 3, 1],
       [1, 3, 2],
       [1, 3, 1],
       [1, 3, 2],
       [1, 3, 2],
       [0, 4, 2],
       [1, 4, 1],
       [1,

In [49]:
y = data[["food_LE"]].values
z = data[["drink_LE"]].values
v = data[["food_LE", "drink_LE"]].values

In [ ]:
y

In [ ]:
z

Train test split (use if you have 1000 data or more)

In [20]:
X_train_data, X_test_data, y_train_data, y_test_data = train_test_split(X , y, test_size = 0.3)

In [21]:
Xz_train_data, Xz_test_data, z_train_data, z_test_data = train_test_split(X, z, test_size = 0.3)

Transfor to OneHotEncoding

In [50]:
X = ohe.fit_transform(X).toarray()
X

array([[1., 0., 0., 0., 0., 1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1., 0., 0., 0., 1., 0.],
       [1., 0., 1., 0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 1., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 1., 0., 0., 0., 1.],
       [1., 0., 1., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 1., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 1., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 1., 0., 0., 0., 1.],
       [1., 0., 0., 

In [51]:
y = ohe.fit_transform(y).toarray()
y

array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 

In [52]:
z = ohe.fit_transform(z).toarray()
z

array([[0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 

In [ ]:
v = ohe.fit_transform(v).toarray()
v

## Classifier model


In [53]:
classifier = DecisionTreeClassifier()
classifierDrink = DecisionTreeClassifier()
classifier.fit(X, y)
classifierDrink.fit(X, z)

DecisionTreeClassifier()

In [54]:
y_class_pred = classifier.predict(X)
z_class_pred = classifierDrink.predict(X)

## Regression model (doesn't work)

In [55]:
regressorFood = DecisionTreeRegressor(random_state=0)
regressorDrink = DecisionTreeRegressor(random_state=0)
regressorFood.fit(X_train_data, y_train_data)
regressorDrink.fit(Xz_train_data, z_train_data)

DecisionTreeRegressor(random_state=0)

In [56]:
y_pred = regressorFood.predict(X_test_data)
z_pred = regressorDrink.predict(X_test_data)

## Random Forest

In [27]:
forest_classY = RandomForestClassifier(500)
forest_classZ = RandomForestClassifier(500)

In [28]:
forest_classY.fit(X, y)
forest_classZ.fit(X, z)

RandomForestClassifier(n_estimators=500)

In [29]:
forest_classY_pred = forest_classY.predict(X)
forest_classZ_pred = forest_classZ.predict(X)

FOR ACCURACY

In [30]:
from sklearn.metrics import classification_report

In [ ]:
print(classification_report(y, y_class_pred))

Classifier

In [32]:
from sklearn.metrics import accuracy_score

In [57]:
ClassAcc = accuracy_score(y, y_class_pred)
DrinkAcc = accuracy_score(z, z_class_pred)
print(ClassAcc)
print(DrinkAcc)

0.27472527472527475
0.27472527472527475


Random forest

In [34]:
forestYAcc = accuracy_score(y, forest_classY_pred)
forestZAcc = accuracy_score(z, forest_classZ_pred)
print(forestYAcc)
print(forestZAcc)

0.27472527472527475
0.2857142857142857


Regression

In [ ]:
foodAcc = accuracy_score(y_test_data, y_pred)
drinkAcc = accuracy_score(z_test_data, z_pred)
print(f"Food accuracy: ", foodAcc * 100)
print(f"Drink accuracy: ", drinkAcc * 100)