# Read Only, Don't Execute

Change ";" into ","

In [ ]:
import os
with open('model/test.csv', 'r') as file:
    filedata = file.read()
    filedata = filedata.replace(';', ',')

    with open('model/test.csv', 'w') as file:
        file.write(filedata)

To inverse Label encoding, simply run

<font color = 'red'>[corresponding Label Encoder variable]</font>.inverse_transform(<font color = 'red'>[value]</font>)

Example

In [ ]:
#leA = Label Encoder for age
#leA.inverse_transform([0])
#will print out "Anak - anak"

To inverse OneHotEncoder however:

In [ ]:
#y is the variable that's already encoded
#for i in y:
  #i = np.argmax(i)

# CODE STARTS HERE

In [1]:
import numpy as np
import seaborn as sns
import pandas as pd
from sklearn.tree import DecisionTreeRegressor
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [2]:
data = pd.read_csv("model/survey.csv")
data.head()

Jenis Kelamin  Umur Lokasi    Mood Rekomendasi Makanan Rekomendasi Minuman
0   Laki - Laki    17    NaN  Senang         Nasi goreng     Minuman bersoda
1   Laki - Laki    17    NaN  Senang             Cokelat     Minuman bersoda
2   Laki - Laki    17    NaN   Marah           Mie pedas         Air mineral
3   Laki - Laki    20    NaN   Marah              Seblak         Air mineral
4   Laki - Laki    25    NaN   Sedih       Sayur-sayuran                 Teh

In [3]:
data['Lokasi'] = data['Lokasi'].fillna("Tidak Tersedia")
data.head()

Jenis Kelamin  Umur          Lokasi    Mood Rekomendasi Makanan  \
0   Laki - Laki    17  Tidak Tersedia  Senang         Nasi goreng   
1   Laki - Laki    17  Tidak Tersedia  Senang             Cokelat   
2   Laki - Laki    17  Tidak Tersedia   Marah           Mie pedas   
3   Laki - Laki    20  Tidak Tersedia   Marah              Seblak   
4   Laki - Laki    25  Tidak Tersedia   Sedih       Sayur-sayuran   

  Rekomendasi Minuman  
0     Minuman bersoda  
1     Minuman bersoda  
2         Air mineral  
3         Air mineral  
4                 Teh

## Encoding 

In [4]:
data["Umur"].unique()

array([17, 20, 25, 18, 11, 12, 15,  7,  8,  6, 10, 30, 16,  5, 70, 75, 28,
       60, 80, 90, 35, 27, 50, 55, 21, 24, 37], dtype=int64)

In [5]:
def simplify_age (age):
    if age > 0 and age <= 6:
        return "Balita"
    elif age > 6 and age <= 12:
        return "Anak - anak"
    elif age > 12 and age <= 18:
        return "Remaja"
    elif age > 18 and age <= 65:
        return "Dewasa"
    elif age > 65 and age <= 200:
        return "lansia"
    else:
        return "Tidak normal"

data["Umur"] = data["Umur"].apply(simplify_age)
data["Umur"].unique()

array(['Remaja', 'Dewasa', 'Anak - anak', 'Balita', 'lansia'],
      dtype=object)

In [6]:
sex = data["Jenis Kelamin"]
age = data["Umur"]
mood = data["Mood"]
food = data["Rekomendasi Makanan"]
drink = data['Rekomendasi Minuman']

In [7]:
data.loc[drink == 'susu', 'Rekomendasi Minuman'] = 'Susu'

In [8]:
sex.value_counts()

Perempuan      55
Laki - Laki    44
Name: Jenis Kelamin, dtype: int64

In [9]:
age.value_counts()

Remaja         49
Dewasa         24
Anak - anak    16
lansia          7
Balita          3
Name: Umur, dtype: int64

In [10]:
food.value_counts()

Cokelat            17
Nasi goreng        16
Seblak             16
Mie pedas          14
Daging             10
Sayur-sayuran       8
Ikan-ikanan         6
Telur               5
Makanan laut        4
Kacang-kacangan     3
Name: Rekomendasi Makanan, dtype: int64

In [11]:
drink.value_counts()

Air mineral        21
Minuman bersoda    18
Es krim            18
Teh                13
Kopi               12
Susu                8
Air kelapa          5
Jus                 4
Name: Rekomendasi Minuman, dtype: int64

In [12]:
data.head()
data.describe()

Jenis Kelamin    Umur  Lokasi    Mood Rekomendasi Makanan  \
count             99      99      99      99                  99   
unique             2       5      36       3                  10   
top        Perempuan  Remaja  Amogus  Senang             Cokelat   
freq              55      49      29      52                  17   

       Rekomendasi Minuman  
count                   99  
unique                   8  
top            Air mineral  
freq                    21

In [13]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder
ohS = OneHotEncoder()
ohM = OneHotEncoder()
ohF = OneHotEncoder()
ohD = OneHotEncoder()
leA = OrdinalEncoder()
leF = LabelEncoder()
leD = LabelEncoder()

## CHANGE DATATYPE TO CATEGORY

In [14]:
data[["Jenis Kelamin", "Umur", "Mood", "Rekomendasi Makanan", "Rekomendasi Minuman"]] = data[["Jenis Kelamin", "Umur", "Mood", "Rekomendasi Makanan", "Rekomendasi Minuman"]].astype('category')

In [15]:
print(f"Jenis Kelamin: ", sex.unique())
print(f"Umur: ", age.unique())
print(f"Mood: ", mood.unique())
print(f"Makanan: ", food.unique())
print(f"Minuman: ", drink.unique())

Jenis Kelamin:  ['Laki - Laki' 'Perempuan']
Umur:  ['Remaja' 'Dewasa' 'Anak - anak' 'Balita' 'lansia']
Mood:  ['Senang' 'Marah' 'Sedih']
Makanan:  ['Nasi goreng' 'Cokelat' 'Mie pedas' 'Seblak' 'Sayur-sayuran' 'Daging'
 'Kacang-kacangan' 'Telur' 'Makanan laut' 'Ikan-ikanan']
Minuman:  ['Minuman bersoda' 'Air mineral' 'Teh' 'Es krim' 'Kopi' 'Air kelapa'
 'Susu' 'Jus']


In [16]:
data["sex_LE"] = data["Jenis Kelamin"]
data["age_LE"] = leA.set_params(categories=[['Balita', 'Anak - anak', 'Remaja', 'Dewasa', 'lansia']]).fit_transform(data[["Umur"]])
data["mood_LE"] = data["Mood"]
data["food_LE"] = leF.fit_transform(data["Rekomendasi Makanan"])
data["drink_LE"] = leD.fit_transform(data["Rekomendasi Minuman"])

In [17]:
data.head()

Jenis Kelamin    Umur          Lokasi    Mood Rekomendasi Makanan  \
0   Laki - Laki  Remaja  Tidak Tersedia  Senang         Nasi goreng   
1   Laki - Laki  Remaja  Tidak Tersedia  Senang             Cokelat   
2   Laki - Laki  Remaja  Tidak Tersedia   Marah           Mie pedas   
3   Laki - Laki  Dewasa  Tidak Tersedia   Marah              Seblak   
4   Laki - Laki  Dewasa  Tidak Tersedia   Sedih       Sayur-sayuran   

  Rekomendasi Minuman       sex_LE  age_LE mood_LE  food_LE  drink_LE  
0     Minuman bersoda  Laki - Laki     2.0  Senang        6         5  
1     Minuman bersoda  Laki - Laki     2.0  Senang        0         5  
2         Air mineral  Laki - Laki     2.0   Marah        5         1  
3         Air mineral  Laki - Laki     3.0   Marah        8         1  
4                 Teh  Laki - Laki     3.0   Sedih        7         7

# MACHINE LEARNING START HERE

In [ ]:
data.head()

Jenis Kelamin    Umur          Lokasi    Mood Rekomendasi Makanan  \
0   Laki - Laki  Remaja  Tidak Tersedia  Senang         Nasi goreng   
1   Laki - Laki  Remaja  Tidak Tersedia  Senang             Cokelat   
2   Laki - Laki  Remaja  Tidak Tersedia   Marah           Mie pedas   
3   Laki - Laki  Dewasa  Tidak Tersedia   Marah              Seblak   
4   Laki - Laki  Dewasa  Tidak Tersedia   Sedih       Sayur-sayuran   

  Rekomendasi Minuman       sex_LE  age_LE mood_LE  food_LE  drink_LE  
0     Minuman bersoda  Laki - Laki     2.0  Senang        6         5  
1     Minuman bersoda  Laki - Laki     2.0  Senang        0         5  
2         Air mineral  Laki - Laki     2.0   Marah        5         1  
3         Air mineral  Laki - Laki     3.0   Marah        8         1  
4                 Teh  Laki - Laki     3.0   Sedih        7         7

In [18]:
from sklearn.model_selection import train_test_split

Put data into variable and make new dataframe

In [19]:
sX = data["sex_LE"].values
mX = data["mood_LE"].values
aX = data["age_LE"].values

In [20]:
d_ohe ={"sex": sX, "mood": mX, "age": aX}

In [21]:
data_ohe = pd.DataFrame(d_ohe)

In [22]:
data_ohe.head()

sex    mood  age
0  Laki - Laki  Senang  2.0
1  Laki - Laki  Senang  2.0
2  Laki - Laki   Marah  2.0
3  Laki - Laki   Marah  3.0
4  Laki - Laki   Sedih  3.0

In [23]:
fY = data["food_LE"].values
dZ = data["drink_LE"].values

In [24]:
y_d_ohe = {"food": fY}
z_d_ohe = {"drink": dZ}

In [25]:
data_y_ohe = pd.DataFrame(y_d_ohe)
data_z_ohe = pd.DataFrame(z_d_ohe)

In [ ]:
data_y_ohe.head()

food
0     6
1     0
2     5
3     8
4     7

In [ ]:
data_z_ohe.head()

drink
0      5
1      5
2      1
3      1
4      7

One Hot Encoded dataframe

In [26]:
data_ohe_oh = pd.get_dummies(data_ohe[["sex"]])
data_ohe = pd.concat([data_ohe, data_ohe_oh], axis = 1)
data_ohe.head()

sex    mood  age  sex_Laki - Laki  sex_Perempuan
0  Laki - Laki  Senang  2.0                1              0
1  Laki - Laki  Senang  2.0                1              0
2  Laki - Laki   Marah  2.0                1              0
3  Laki - Laki   Marah  3.0                1              0
4  Laki - Laki   Sedih  3.0                1              0

In [27]:
data_ohe_oh = pd.get_dummies(data_ohe[["mood"]])
data_ohe = pd.concat([data_ohe, data_ohe_oh], axis = 1)
data_ohe.head()

sex    mood  age  sex_Laki - Laki  sex_Perempuan  mood_Marah  \
0  Laki - Laki  Senang  2.0                1              0           0   
1  Laki - Laki  Senang  2.0                1              0           0   
2  Laki - Laki   Marah  2.0                1              0           1   
3  Laki - Laki   Marah  3.0                1              0           1   
4  Laki - Laki   Sedih  3.0                1              0           0   

   mood_Sedih  mood_Senang  
0           0            1  
1           0            1  
2           0            0  
3           0            0  
4           1            0

In [28]:
data_y_ohe_oh = pd.DataFrame(ohF.fit_transform(data_y_ohe[["food"]]).toarray())
data_y_ohe = pd.concat([data_y_ohe, data_y_ohe_oh], axis=1)
data_y_ohe.head()

food    0    1    2    3    4    5    6    7    8    9
0     6  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
1     0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2     5  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
3     8  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
4     7  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0

In [29]:
data_y_ohe.rename(columns = {0: 'f0', 1: 'f1', 2: 'f2', 3: 'f3', 4: 'f4', 5: 'f5', 6: 'f6', 7: 'f7', 8: 'f8', 9: 'f9'}, inplace=True)
data_y_ohe.head()

food   f0   f1   f2   f3   f4   f5   f6   f7   f8   f9
0     6  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
1     0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2     5  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
3     8  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
4     7  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0

In [30]:
data_z_ohe_oh = pd.DataFrame(ohD.fit_transform(data_z_ohe[["drink"]]).toarray())
data_z_ohe = pd.concat([data_z_ohe, data_z_ohe_oh], axis=1)
data_z_ohe.head()

drink    0    1    2    3    4    5    6    7
0      5  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
1      5  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
2      1  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
3      1  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
4      7  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0

In [31]:
data_z_ohe.rename(columns= {0: 'd0', 1: 'd1', 2: 'd2', 3: 'd3', 4: 'd4', 5: 'd5', 6: 'd6', 7: 'd7'}, inplace=True)
data_z_ohe.head()

drink   d0   d1   d2   d3   d4   d5   d6   d7
0      5  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
1      5  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
2      1  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
3      1  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
4      7  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0

Making whole the fabric of society

In [32]:
data_join = pd.concat([data_ohe, data_y_ohe, data_z_ohe], axis = 1)
data_join.head()

sex    mood  age  sex_Laki - Laki  sex_Perempuan  mood_Marah  \
0  Laki - Laki  Senang  2.0                1              0           0   
1  Laki - Laki  Senang  2.0                1              0           0   
2  Laki - Laki   Marah  2.0                1              0           1   
3  Laki - Laki   Marah  3.0                1              0           1   
4  Laki - Laki   Sedih  3.0                1              0           0   

   mood_Sedih  mood_Senang  food   f0  ...   f9  drink   d0   d1   d2   d3  \
0           0            1     6  0.0  ...  0.0      5  0.0  0.0  0.0  0.0   
1           0            1     0  1.0  ...  0.0      5  0.0  0.0  0.0  0.0   
2           0            0     5  0.0  ...  0.0      1  0.0  1.0  0.0  0.0   
3           0            0     8  0.0  ...  0.0      1  0.0  1.0  0.0  0.0   
4           1            0     7  0.0  ...  0.0      7  0.0  0.0  0.0  0.0   

    d4   d5   d6   d7  
0  0.0  1.0  0.0  0.0  
1  0.0  1.0  0.0  0.0  
2  0.0  0.0  0.0  0.0  
3  0.0  0.0  0.0  0.0  
4  0.0  0.0  0.0  1.0  

[5 rows x 28 columns]

Inserting data into variable

In [34]:
X = data_join[["sex_Laki - Laki", "sex_Perempuan", 'mood_Marah', 'mood_Sedih', 'mood_Senang', 'age']].values
X

array([[1., 0., 0., 0., 1., 2.],
       [1., 0., 0., 0., 1., 2.],
       [1., 0., 1., 0., 0., 2.],
       [1., 0., 1., 0., 0., 3.],
       [1., 0., 0., 1., 0., 3.],
       [0., 1., 0., 0., 1., 2.],
       [1., 0., 0., 0., 1., 1.],
       [0., 1., 0., 0., 1., 1.],
       [0., 1., 1., 0., 0., 2.],
       [0., 1., 0., 0., 1., 2.],
       [1., 0., 0., 1., 0., 1.],
       [0., 1., 0., 0., 1., 1.],
       [0., 1., 1., 0., 0., 0.],
       [1., 0., 0., 1., 0., 1.],
       [1., 0., 0., 0., 1., 1.],
       [1., 0., 0., 0., 1., 3.],
       [1., 0., 0., 1., 0., 2.],
       [0., 1., 1., 0., 0., 2.],
       [1., 0., 1., 0., 0., 2.],
       [1., 0., 0., 0., 1., 2.],
       [1., 0., 0., 1., 0., 3.],
       [1., 0., 0., 1., 0., 2.],
       [1., 0., 1., 0., 0., 2.],
       [0., 1., 1., 0., 0., 2.],
       [0., 1., 0., 0., 1., 2.],
       [1., 0., 0., 0., 1., 2.],
       [1., 0., 0., 1., 0., 2.],
       [0., 1., 0., 0., 1., 2.],
       [0., 1., 0., 0., 1., 2.],
       [0., 1., 0., 1., 0., 2.],
       [0.

In [35]:
y = data_join[['f0', 'f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9']].values
z = data_join[['d0', 'd1', 'd2', 'd3', 'd4', 'd5', 'd6', 'd7']].values
v = data[["food_LE", "drink_LE"]].values

In [ ]:
X

In [ ]:
y

In [ ]:
z

Train test split (use if you have 1000 data or more)

In [36]:
X_train_data, X_test_data, y_train_data, y_test_data = train_test_split(X , y, test_size = 0.3, random_state=1, stratify=y)

In [37]:
Xz_train_data, Xz_test_data, z_train_data, z_test_data = train_test_split(X, z, test_size = 0.3, random_state=1, stratify=y)

In [ ]:
X_train_data

In [ ]:
y_train_data

In [ ]:
X_test_data

## Classifier model


In [ ]:
classifier = DecisionTreeClassifier()
classifierDrink = DecisionTreeClassifier()
classifier.fit(X_train_data, y_train_data)
classifierDrink.fit(Xz_train_data, z_train_data)

DecisionTreeClassifier()

In [38]:
classifier = DecisionTreeClassifier(max_features=None)
classifierDrink = DecisionTreeClassifier(max_features=None)
classifier.fit(X, y)
classifierDrink.fit(X, z)

DecisionTreeClassifier()

In [39]:
test = [[0., 1., 0., 0., 1., 4.]]
true_f = [[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]]
test_pred = classifier.predict(test)
drink_pred = classifierDrink.predict(test)
for i in true_f:
  i = np.argmax(i)
  i = leF.inverse_transform([i])
  print("True food: ", i)
for i in test_pred:
  i = np.argmax(i)
  i = leF.inverse_transform([i])
  print(i)
for i in drink_pred:
  i = np.argmax(i)
  i = leD.inverse_transform([i])
  print(i)
print(test_pred)

True food:  ['Nasi goreng']
['Sayur-sayuran']
['Kopi']
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]


In [40]:
y_class_pred = classifier.predict(X_test_data)
z_class_pred = classifierDrink.predict(Xz_test_data)

In [ ]:
y_class_pred = classifier.predict(X)
z_class_pred = classifierDrink.predict(X)

## Regression model (doesn't work)

In [ ]:
regressorFood = DecisionTreeRegressor(random_state=0)
regressorDrink = DecisionTreeRegressor(random_state=0)
regressorFood.fit(X_train_data, y_train_data)
regressorDrink.fit(Xz_train_data, z_train_data)

DecisionTreeRegressor(random_state=0)

In [ ]:
y_pred = regressorFood.predict(X_test_data)
z_pred = regressorDrink.predict(X_test_data)

## Random Forest

In [47]:
forest_classY = RandomForestClassifier(200)
forest_classZ = RandomForestClassifier(200)

In [48]:
forest_classY.fit(X, y)
forest_classZ.fit(X, z)

RandomForestClassifier(n_estimators=200)

In [ ]:
forest_classY.fit(X_train_data, y_train_data)
forest_classZ.fit(Xz_train_data, z_train_data)

RandomForestClassifier(n_estimators=200)

In [49]:
forest_classY_pred = forest_classY.predict(X_test_data)
forest_classZ_pred = forest_classZ.predict(Xz_test_data)

Test random forest

In [52]:
test = [[0., 1., 0., 0., 1., 4.]]
true_f = [[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]]
forest_test_pred = forest_classY.predict(test)
forest_drink_pred = forest_classZ.predict(test)
for i in true_f:
  i = np.argmax(i)
  i = leF.inverse_transform([i])
  print("True food: ", i)
for i in forest_test_pred:
  i = np.argmax(i)
  i = leF.inverse_transform([i])
  print(i)
for i in forest_drink_pred:
  i = np.argmax(i)
  i = leD.inverse_transform([i])
  print(i)
print(forest_test_pred)

True food:  ['Nasi goreng']
['Sayur-sayuran']
['Kopi']
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]


# FOR ACCURACY

In [41]:
from sklearn.metrics import classification_report

SPLIT TRAIN TEST REPORT

In [42]:
print(classification_report(y_test_data, y_class_pred))

              precision    recall  f1-score   support

           0       0.50      0.40      0.44         5
           1       0.00      0.00      0.00         3
           2       0.00      0.00      0.00         2
           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         1
           5       0.75      0.75      0.75         4
           6       1.00      0.20      0.33         5
           7       1.00      0.50      0.67         2
           8       0.00      0.00      0.00         5
           9       1.00      0.50      0.67         2

   micro avg       0.67      0.27      0.38        30
   macro avg       0.42      0.24      0.29        30
weighted avg       0.48      0.27      0.32        30
 samples avg       0.27      0.27      0.27        30



c:\Users\senoa.DESKTOP-TRKAE2C\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\senoa.DESKTOP-TRKAE2C\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [43]:
print(classification_report(z_test_data, z_class_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.67      0.33      0.44         6
           2       0.60      0.50      0.55         6
           3       1.00      1.00      1.00         1
           4       0.67      0.40      0.50         5
           5       1.00      0.25      0.40         4
           6       0.00      0.00      0.00         2
           7       1.00      0.20      0.33         5

   micro avg       0.71      0.33      0.45        30
   macro avg       0.62      0.34      0.40        30
weighted avg       0.70      0.33      0.42        30
 samples avg       0.33      0.33      0.33        30



c:\Users\senoa.DESKTOP-TRKAE2C\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\senoa.DESKTOP-TRKAE2C\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


NOT SPLIT REPORT

In [ ]:
print(classification_report(y, y_class_pred))

In [ ]:
print(classification_report(z, z_class_pred))

NOT SPLIT FOREST REPORT

In [ ]:
print(classification_report(y_test_data, forest_classY))

In [ ]:
print(classification_report(z_test_data, forest_classZ))

Classifier

In [44]:
from sklearn.metrics import accuracy_score

In [45]:
ClassAcc = accuracy_score(y_test_data, y_class_pred)
DrinkAcc = accuracy_score(z_test_data, z_class_pred)
print(ClassAcc)
print(DrinkAcc)

0.26666666666666666
0.3333333333333333


In [ ]:
ClassAcc = accuracy_score(y, y_class_pred)
DrinkAcc = accuracy_score(z, z_class_pred)
print(ClassAcc)
print(DrinkAcc)

0.25252525252525254
0.24242424242424243


Random forest

In [ ]:
forestYAcc = accuracy_score(y_test_data, forest_classY_pred)
forestZAcc = accuracy_score(z_test_data, forest_classZ_pred)
print(forestYAcc)
print(forestZAcc)

0.26666666666666666
0.3333333333333333


Regression

In [ ]:
foodAcc = accuracy_score(y_test_data, y_pred)
drinkAcc = accuracy_score(z_test_data, z_pred)
print(f"Food accuracy: ", foodAcc * 100)
print(f"Drink accuracy: ", drinkAcc * 100)

# Testing

In [ ]:
X

In [1]:
test = [[0., 1., 0., 0., 1., 4.]]

In [ ]:
testF_pred = forest_classY.predict(test)
testD_pred = forest_classZ.predict(test)

In [ ]:
print(testF_pred)
print(testD_pred)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0.]]


# Saving the model

In [46]:
import pickle

In [53]:
saved_model = {"model_food": forest_classY, "model_drink": forest_classZ, "age_ENC": leA,
                "food_ENC": leF, "drink_ENC": leD, "food_ohe": ohF, "drink_ohe": ohD
                }
with open("saved_model.pkl", 'wb') as file:
    pickle.dump(saved_model, file)

# TEST PICKLE

In [55]:
with open('saved_model.pkl', 'rb') as file:
    model = pickle.load(file)

#model
forestModelFood = model["model_food"]
forestModelDrink = model["model_drink"]

#encoder
age_LE = model["age_ENC"]
food_LE = model["food_ENC"]
drink_LE = model["drink_ENC"]

food_ohe = model["food_ohe"]
drink_ohe = model["drink_ohe"]