Change ";" into ","

In [ ]:
import os
with open('model/test.csv', 'r') as file:
    filedata = file.read()
    filedata = filedata.replace(';', ',')

    with open('model/test.csv', 'w') as file:
        file.write(filedata)

CODE STARTS HERE

In [2]:
import numpy as np
import seaborn as sns
import pandas as pd
from sklearn.tree import DecisionTreeRegressor

In [4]:
data = pd.read_csv("model/survey.csv")
data.head()

Jenis Kelamin  Umur Lokasi    Mood Rekomendasi Makanan Rekomendasi Minuman
0   Laki - Laki    17    NaN  Senang         Nasi goreng     Minuman bersoda
1   Laki - Laki    17    NaN  Senang             Cokelat     Minuman bersoda
2   Laki - Laki    17    NaN   Marah           Mie pedas         Air mineral
3   Laki - Laki    20    NaN   Marah              Seblak         Air mineral
4   Laki - Laki    25    NaN   Sedih       Sayur-sayuran                 Teh

In [5]:
data['Lokasi'] = data['Lokasi'].fillna("Tidak Tersedia")
data.head()

Jenis Kelamin  Umur          Lokasi    Mood Rekomendasi Makanan  \
0   Laki - Laki    17  Tidak Tersedia  Senang         Nasi goreng   
1   Laki - Laki    17  Tidak Tersedia  Senang             Cokelat   
2   Laki - Laki    17  Tidak Tersedia   Marah           Mie pedas   
3   Laki - Laki    20  Tidak Tersedia   Marah              Seblak   
4   Laki - Laki    25  Tidak Tersedia   Sedih       Sayur-sayuran   

  Rekomendasi Minuman  
0     Minuman bersoda  
1     Minuman bersoda  
2         Air mineral  
3         Air mineral  
4                 Teh

Encoding 

In [6]:
def simplify_age (age):
    if age > 0 and age < 6:
        return "Balita"
    elif age > 6 and age < 12:
        return "Anak - anak"
    elif age > 12 and age < 18:
        return "Remaja"
    elif age > 18 and age < 65:
        return "Dewasa"
    elif age > 65 and age < 200:
        return "lansia"
    return "Tidak normal"

data["Umur"] = data["Umur"].apply(simplify_age)
data["Umur"].unique()

array(['Remaja', 'Dewasa', 'Tidak normal', 'Anak - anak', 'Balita',
       'lansia'], dtype=object)

In [19]:
sex = data["Jenis Kelamin"]
age = data["Umur"]
mood = data["Mood"]
food = data["Rekomendasi Makanan"]
drink = data['Rekomendasi Minuman']

In [ ]:
sex.value_counts()

Perempuan      55
Laki - Laki    44
Name: Jenis Kelamin, dtype: int64

In [ ]:
age.value_counts()

Remaja         44
Dewasa         24
Anak - anak    15
lansia          7
Balita          2
Name: Umur, dtype: int64

In [7]:
data = data[data.Umur != "Tidak normal"]
data = data[data["Rekomendasi Minuman"] != "susu"]

In [12]:
data.head()
data.describe()

Jenis Kelamin    Umur  Lokasi    Mood Rekomendasi Makanan  \
count             91      91      91      91                  91   
unique             2       5      34       3                  10   
top        Perempuan  Remaja  Amogus  Senang         Nasi goreng   
freq              49      44      28      49                  16   

       Rekomendasi Minuman  
count                   91  
unique                   8  
top            Air mineral  
freq                    19

In [9]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
ohe = OneHotEncoder()
le = LabelEncoder()

CHANGE DATATYPE TO CATEGORY

In [18]:
data[["Jenis Kelamin", "Umur", "Mood", "Rekomendasi Makanan", "Rekomendasi Minuman"]] = data[["Jenis Kelamin", "Umur", "Mood", "Rekomendasi Makanan", "Rekomendasi Minuman"]].astype('category')

In [26]:
print(f"Jenis Kelamin: ", sex.unique())
print(f"Umur: ", age.unique())
print(f"Mood: ", mood.unique())
print(f"Makanan: ", food.unique())
print(f"Minuman: ", drink.unique())

Jenis Kelamin:  ['Laki - Laki', 'Perempuan']
Categories (2, object): ['Laki - Laki', 'Perempuan']
Umur:  ['Remaja', 'Dewasa', 'Anak - anak', 'Balita', 'lansia']
Categories (5, object): ['Anak - anak', 'Balita', 'Dewasa', 'Remaja', 'lansia']
Mood:  ['Senang', 'Marah', 'Sedih']
Categories (3, object): ['Marah', 'Sedih', 'Senang']
Makanan:  ['Nasi goreng', 'Cokelat', 'Mie pedas', 'Seblak', 'Sayur-sayuran', 'Daging', 'Kacang-kacangan', 'Makanan laut', 'Ikan-ikanan', 'Telur']
Categories (10, object): ['Cokelat', 'Daging', 'Ikan-ikanan', 'Kacang-kacangan', ...,
                          'Nasi goreng', 'Sayur-sayuran', 'Seblak', 'Telur']
Minuman:  ['Minuman bersoda', 'Air mineral', 'Teh', 'Es krim', 'Kopi', 'Air kelapa', 'Susu', 'Jus']
Categories (8, object): ['Air kelapa', 'Air mineral', 'Es krim', 'Jus', 'Kopi', 'Minuman bersoda',
                         'Susu', 'Teh']


In [ ]:
data["Jenis Kelamin"] = le.fit_transform(data["Jenis Kelamin"])
data["Umur"] = le.fit_transform(data["Umur"])
data["Mood"] = le.fit_transform(data["Mood"])
data["Rekomendasi Makanan"] = le.fit_transform(data["Rekomendasi Makanan"])
data["Rekomendasi Minuman"] = le.fit_transform(data["Rekomendasi Minuman"])

In [ ]:
data.head()

Jenis Kelamin  Umur          Lokasi  Mood  Rekomendasi Makanan  \
0              0     3  Tidak Tersedia     2                    6   
1              0     3  Tidak Tersedia     2                    0   
2              0     3  Tidak Tersedia     0                    5   
3              0     2  Tidak Tersedia     0                    8   
4              0     2  Tidak Tersedia     1                    7   

   Rekomendasi Minuman  
0                    5  
1                    5  
2                    1  
3                    1  
4                    7

In [ ]:
ohe.categories_

[array([0, 1], dtype=int64)]

USE TO INVERSE

In [ ]:
np.argmax(data['Jenis Kelamin'], axis = 1)

MACHINE LEARNING START HERE

In [ ]:
data.head()

Jenis Kelamin  Umur          Lokasi  Mood  Rekomendasi Makanan  \
0              0     3  Tidak Tersedia     2                    6   
1              0     3  Tidak Tersedia     2                    0   
2              0     3  Tidak Tersedia     0                    5   
3              0     2  Tidak Tersedia     0                    8   
4              0     2  Tidak Tersedia     1                    7   

   Rekomendasi Minuman  
0                    5  
1                    5  
2                    1  
3                    1  
4                    7

In [ ]:
X = data[["Jenis Kelamin","Umur", "Mood"]].values
X

array([[0, 3, 2],
       [0, 3, 2],
       [0, 3, 0],
       [0, 2, 0],
       [0, 2, 1],
       [0, 0, 2],
       [1, 3, 0],
       [1, 3, 2],
       [0, 0, 1],
       [1, 0, 2],
       [0, 0, 1],
       [0, 0, 2],
       [0, 2, 2],
       [0, 3, 1],
       [1, 3, 0],
       [0, 3, 2],
       [0, 2, 1],
       [0, 3, 0],
       [1, 3, 0],
       [0, 3, 2],
       [0, 3, 1],
       [1, 3, 2],
       [1, 3, 2],
       [1, 3, 1],
       [1, 3, 2],
       [1, 3, 2],
       [1, 3, 2],
       [1, 3, 2],
       [1, 3, 2],
       [1, 2, 2],
       [1, 3, 1],
       [0, 3, 2],
       [0, 3, 2],
       [1, 3, 0],
       [1, 3, 2],
       [0, 2, 2],
       [1, 3, 2],
       [0, 3, 0],
       [0, 1, 2],
       [0, 3, 2],
       [1, 3, 2],
       [0, 0, 2],
       [1, 0, 2],
       [0, 0, 0],
       [1, 0, 0],
       [1, 3, 2],
       [1, 3, 2],
       [1, 3, 1],
       [1, 3, 1],
       [1, 3, 2],
       [1, 3, 1],
       [1, 3, 2],
       [1, 3, 2],
       [0, 4, 2],
       [1, 4, 1],
       [1,

In [ ]:
y = data[["Rekomendasi Makanan"]].values
z = data[["Rekomendasi Minuman"]].values

In [ ]:
y

array([[6],
       [0],
       [5],
       [8],
       [7],
       [1],
       [8],
       [6],
       [7],
       [3],
       [1],
       [6],
       [8],
       [8],
       [8],
       [5],
       [1],
       [1],
       [5],
       [6],
       [0],
       [4],
       [8],
       [0],
       [5],
       [1],
       [5],
       [4],
       [6],
       [2],
       [8],
       [9],
       [4],
       [8],
       [9],
       [8],
       [8],
       [7],
       [9],
       [9],
       [6],
       [0],
       [0],
       [6],
       [8],
       [5],
       [1],
       [8],
       [0],
       [4],
       [5],
       [3],
       [8],
       [7],
       [0],
       [1],
       [6],
       [1],
       [5],
       [2],
       [0],
       [5],
       [2],
       [1],
       [7],
       [7],
       [5],
       [8],
       [6],
       [0],
       [5],
       [6],
       [0],
       [8],
       [6],
       [0],
       [7],
       [0],
       [2],
       [6],
       [6],
       [2],
       [5],
    

In [ ]:
X = ohe.fit_transform(X).toarray()
X

array([[1., 0., 0., 0., 0., 1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1., 0., 0., 0., 1., 0.],
       [1., 0., 1., 0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 1., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 1., 0., 0., 0., 1.],
       [1., 0., 1., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 1., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 1., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 1., 0., 0., 0., 1.],
       [1., 0., 0., 

In [ ]:
y = ohe.fit_transform(y).toarray()
y

array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 

In [ ]:
z = ohe.fit_transform(z).toarray()
z

array([[0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 

In [ ]:
regressorFood = DecisionTreeRegressor(random_state=0)
regressorDrink = DecisionTreeRegressor(random_state=0)
regressorFood.fit(X, y)
regressorDrink.fit(X,z)

DecisionTreeRegressor(random_state=0)

In [ ]:
y_pred = regressorFood.predict(X)
z_pred = regressorDrink.predict(X)

FOR ACCURACY

In [ ]:
foodAcc = regressorFood.score(X, y)
drinkAcc = regressorDrink.score(X, z)
print(f"Food accuracy: ", foodAcc * 100)
print(f"Drink accuracy: ", drinkAcc * 100)

Food accuracy:  27.249771139735845
Drink accuracy:  24.969032292527178
